<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>BASALEH GLOBAL SERVICES LTD | About Us</title>
<!-- Stylesheets -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;family=Nunito+Sans:wght@300;600;700;800;900&amp;display=swap" rel="stylesheet">

<!-- Color Switcher Mockup -->
<link href="css/color-switcher-design.css" rel="stylesheet">

<!-- Color Themes -->
<link id="theme-color-file" href="css/color-themes/default-theme.css" rel="stylesheet">

<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
<link rel="icon" href="images/favicon.png" type="image/x-icon">

<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
</head>

<body class="hidden-bar-wrapper">

<div class="page-wrapper">
 	
    <!-- Preloader -->
    <div class="preloader"></div>
 	
 	<!-- Main Header-->
    <header class="main-header header-style-one">
    	
		<!-- Header Top -->
        <div class="header-top">
            <div class="auto-container">
                <div class="clearfix">
					<!-- Top Left -->
					<div class="top-left">
						<!-- Info List -->
						<ul class="info-list">
							<li><a href="mailto:info@webmail.com"><span class="icon flaticon-email"></span> info@basalehglobal.ng</a></li>
							<li><a href="tel:786-875-864-75"><span class="icon flaticon-telephone"></span> 08038012451, 08174212145</a></li>
						</ul>
					</div>
					
					<!-- Top Right -->
                    <div class="top-right pull-right">
						<!-- Social Box -->
						<ul class="social-box">
							<li><a href="#" class="fa fa-facebook-f"></a></li>
							<li><a href="#" class="fa fa-twitter"></a></li>
							<li><a href="#" class="fa fa-dribbble"></a></li>
							<li><a href="#" class="fa fa-google"></a></li>
						</ul>
                    </div>
					
                </div>
            </div>
        </div>
		
		<!--Header-Upper-->
        <div class="header-upper">
        	<div class="auto-container clearfix">
            	
				<div class="pull-left logo-box">
					<div class="logo"><a href="https://basalehglobal.com"><img src="images/logo-2.png" alt="" title=""></a></div>
				</div>
				
				<div class="nav-outer clearfix">
					<!--Mobile Navigation Toggler-->
					<div class="mobile-nav-toggler"><span class="icon flaticon-menu"></span></div>
					<!-- Main Menu -->
					<nav class="main-menu navbar-expand-md">
						<div class="navbar-header">
							<!-- Toggle Button -->    	
							<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						
						<div class="navbar-collapse collapse clearfix" id="navbarSupportedContent">
							<ul class="navigation clearfix">
								<li><a href="https://basalehglobal.com">Home</a>
								</li>
								<li class="current dropdown"><a href="#">who we Are</a>
									<ul>
										<li><a href="about.PHP">About Us</a></li>
											<li><a href="team.PHP">Team</a></li>
											<li><a href="mission.PHP">Vision</a></li>
											<li><a href="mission.PHP">Mission</a></li>
									</ul>
								</li>
								<li class="dropdown"><a href="#">Application</a>
										<ul>
											<li><a href="#.PHP">Certificate</a></li>
										</ul>
									</li>
										<li><a href="services.PHP">Services</a></li>
								<li><a href="contact.PHP">Contact us</a></li>
							</ul>
						</div>
					</nav>
					
					<!-- Main Menu End-->
					<div class="outer-box clearfix">
							
					</div>
				</div>
				
            </div>
        </div>
        <!--End Header Upper-->
        
		<!-- Sticky Header  -->
        <div class="sticky-header">
            <div class="auto-container clearfix">
                <!--Logo-->
                <div class="logo pull-left">
                    <a href="https://basalehglobal.com" title=""><img src="images/logo-2.png" alt="" title=""></a>
                </div>
                <!--Right Col-->
                <div class="pull-right">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav><!-- Main Menu End-->
					
					<!-- Main Menu End-->
					<div class="outer-box clearfix">
						
					</div>
					
                </div>
            </div>
        </div><!-- End Sticky Menu -->
    
		<!-- Mobile Menu  -->
        <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><span class="icon flaticon-multiply"></span></div>
            
            <nav class="menu-box">
                <div class="nav-logo"><a href="https://basalehglobal.com"><img src="images/logo-2.png" alt="" title=""></a></div>
                <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
            </nav>
        </div><!-- End Mobile Menu -->
	
    </header>
    <!-- End Main Header -->
	
	
	<!--Page Title-->
    <section class="page-title">
		<div class="pattern-layer-one" style="background-image: url(images/background/pattern-16.png)"></div>
    	<div class="auto-container">
			<h2>About us</h2>
			<ul class="page-breadcrumb">
				<li><a href="https://basalehglobal.com">home</a></li>
				<li>About us</li>
			</ul>
        </div>
    </section>
    <!--End Page Title-->
	
	<!-- About Section -->
	<section class="about-section">
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title">
				<div class="title">ABOUT THE COMPANY</div>
				<h2>BASALEH GLOBAL<br> SERVICES LIMITED</h2>
			</div>
			<div class="row clearfix">
				
				<!-- Content Column -->
				<div class="content-column col-lg-6 col-md-12 col-sm-12">
					<div class="inner-column">
						<div class="text"> provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.
							<p>Since its inception BASALEH GLOBAL SERVICES LIMITED has maintained good record in quality service and time delivery in Consultancy services Supply and Installation, hardware/Software and network solution.</p>
							<p>BASALEH GLOBAL SERVICES LIMITED focuses exclusively in high quality and cost-effective system development and implementation of multiple type of services. We are advancing on a tremendous pace and with involvement of skilled and experienced people working in the organization.</p></div>
						<div class="blocks-outer">
						
							<!-- Feature Block -->
							<div class="inner-column">
								<div class="inner-box">
									<h3 style="color: #000; font-weight: 300px">BASALEH TECHNOLOGIES</h3>
									<img img src="images/services/about.jpg" height="50%" class="pull-left">
									<div class="text">   Professionals with huge experience and wide exposure in Communications and Information Technology is the backbone of BASALEH GLOBAL SERVICES LIMITED. People involved here are young qualified business graduates and qualified engineers from the renowned universities across the globe.<p>The resource personnel working in the company have been consistently providing reliable support</p>
									<p>services and consultancy to a wide variety of corporate houses either in the capacity of executive or as business partner or consultant. Bottom line of the company philosophy is building a long-term business partnership with its clients where interpersonal relationship, reliability, assured quality and target oriented modern technology are the major building blocks.</p>

									<p>It is a company where professionals from both technical and functional field group together with an objective of providing appropriate business solutions. It realizes the importance of functional knowledge and its impact in developing business solutions. We constantly strive to be a leading technology firm with profound business and functional knowledge. The key to the company's success is the maintenance of a close working relationship with the clients through ensuring the best possible solutions to their needs; to establish and maintain a thorough knowledge and understanding of client's objective and help them maximize the benefits. 
									We want to establish ourselves as the best choice in Computing and Information Technology Services, Consultancy and Development by offering the full spectrum of services.
									</p>
								</div>
								</div>
							</div>
						</div>
						
					</div>
				</div>
				
				<!-- Images Column -->
				<div class="images-column col-lg-6 col-md-12 col-sm-12">
					<div class="inner-column" style="background-image: url(images/icons/globe.png)">
						<div class="pattern-layer" style="background-image: url(images/background/pattern-1.png)"></div>
						<div class="images-outer parallax-scene-1">
							<div class="image" data-depth="0.10">
								<img src="images/resource/about-1.jpg" alt="" />
							</div>
							<div class="image-two" data-depth="0.30">
								<img src="images/resource/about-2.jpg" alt="" />
							</div>
							<div class="image-three" data-depth="0.20">
								<img src="images/resource/about-3.jpg" alt="" />
							</div>
							<div class="image-four" data-depth="0.30">
								<img src="images/resource/about-4.jpg" alt="" />
							</div>
						</div>
					</div>
				<div class="row clearfix">
				<br>
				<!-- Testimonial Block -->
				<div class="testimonial-block col-lg-6 col-md-12 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
					<div class="inner-box" style="background-image: url(images/background/pattern-4.png)">
						<div class="upper-box">
							<div class="pull-left icon">
							<img src="images/resource/testimonial-icon-1.png" alt=""height="20px"/>
							</div><br>
							<h4 style="text-align: center;">MISSION</h4>
						</div>
						<div class="text">Our Mission is to achieve the reputation of a quality, high standard & reliable solution & service Provider Company in the ICT and Communications industry.</div>
					</div>
				</div>
				
				<!-- Testimonial Block -->
				<div class="testimonial-block col-lg-6 col-md-5 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="802ms">
					<div class="inner-box" style="background-image: url(images/background/pattern-4.png)">
						<div class="upper-box">
							<div class="icon">
								<img src="images/resource/testimonial-icon-2.png" alt="" />
							</div>
							<h4>VISSION</h4>
						</div>
						<div class="text">"Our Vision is to achieve 100% customer satisfaction by delivering quality products and services at an affordable cost. Our forward vision is to strive to become an entity in technology based corporate solutions.</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End About Section -->
	
	<!-- Call To Action Section -->
	<section class="call-to-action-section" style="background-image: url(images/background/pattern-3.png)">
		<div class="auto-container">
			<div class="row clearfix">
				<!-- Heading Column -->
				<div class="heading-column col-lg-8 col-md-12 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
					<div class="inner-column">
						<h2 style="color: #ffffff; font-size: 26px; font-weight: 500px;">Together with our partners, we provide custom full design of Mission Critical TETRA networks for complete secure communications solutions</h2>
					</div>
				</div>
				<!-- Button Column -->
				<div class="button-column col-lg-4 col-md-12 col-sm-12">
					<div class="inner-column">
						<a href="contact.PHP" class="theme-btn btn-style-two"><span class="txt">Contact Us</span></a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Call To Action Section -->

	<!-- Process Section
    <section class="process-section">
		<div class="pattern-layer-one" style="background-image: url(images/background/pattern-11.jpg)"></div>
		<div class="pattern-layer-two" style="background-image: url(images/background/pattern-12.jpg)"></div>
		<div class="auto-container">
			<div class="sec-title centered">
				<div class="title">OUR PROCESS</div>
				<h2>Driving Client Results Utilizing New <br> Innovation Points of view</h2>
			</div>
			<div class="row clearfix">
				
				<div class="process-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="number-box">01</div>
						<h4><a href="services-detail.PHP">End to End Solutions and Services Guaranteed</a></h4>
						<div class="text">Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. per inceptos himenaeos.</div>
						<a class="read-more" href="services-detail.PHP"><span class="arrow flaticon-long-arrow-pointing-to-the-right"></span>Read More</a>
					</div>
				</div>
				
				<div class="process-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="number-box">02</div>
						<h4><a href="services-detail.PHP">Ahead of The Curve We Future-proof Your IT</a></h4>
						<div class="text">Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. per inceptos himenaeos.</div>
						<a class="read-more" href="services-detail.PHP"><span class="arrow flaticon-long-arrow-pointing-to-the-right"></span>Read More</a>
					</div>
				</div>
				
				<div class="process-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInRight" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="number-box">03</div>
						<h4><a href="services-detail.PHP">Experience Certainty Every Project Executed Successful</a></h4>
						<div class="text">Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. per inceptos himenaeos.</div>
						<a class="read-more" href="services-detail.PHP"><span class="arrow flaticon-long-arrow-pointing-to-the-right"></span>Read More</a>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- End Process Section -->
	
	
	
	<!-- Info Section -->
	<section class="info-section" style="background-image: url(images/background/6.jpg)">
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- Logo Column -->
				<div class="logo-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="logo">
							<a href="https://basalehglobal.com"><img src="images/logo-2.png" alt="" /></a>
						</div>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-pin"></span></div>
						<ul>
							<li><strong>Address</strong></li>
							<li>G6, Barumak Estate, Wuye Abuja.</li>
						</ul>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-phone-call"></span></div>
						<ul>
							<li><strong>Phone</strong></li>
							<li>(+234) 08038012451, 08174212145</li>
						</ul>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-email-1"></span></div>
						<ul>
							<li><strong>E-Mail</strong></li>
							<li>info@basalehglobal.ng</li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- End Info Section -->
	
	<!-- Main Footer -->
    <footer class="main-footer style-three">
		<div class="pattern-layer-three" style="background-image: url(images/background/pattern-14.png)"></div>
		<div class="pattern-layer-four" style="background-image: url(images/background/pattern-15.png)"></div>
		<!--Waves end-->
    	<div class="auto-container">
        	<!--Widgets Section-->
            <div class="widgets-section">
            	<div class="row clearfix">
                	
					<!-- Footer Column -->
					<div class="footer-column col-lg-4 col-md-6 col-sm-12 wow zoomIn"data-wow-delay="0ms" data-wow-duration="800ms">
						<div class="footer-widget logo-widget">
							<h5>About Company</h5>
							<div class="text">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.</div>
						</div>
					</div>
					
					<!-- Footer Column -->
					<div class="footer-column col-lg-3 col-md-6 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
						<div class="footer-widget links-widget">
							<h5>Quick Links</h5>
							<ul class="list-link">
								<li><a href="#">Managed IT services</a></li>
								<li><a href="#">Cloud Services</a></li>
								<li><a href="#">IT support & helpdesk</a></li>
								<li><a href="#">Cyber security</a></li>
								<li><a href="#">Custom Software</a></li>
								<li><a href="#">Free Consultation</a></li>
								<li><a href="#">Our Business Growth</a></li>
							</ul>
						</div>
					</div>
					
                    <!-- Footer Column -->
					<div class="footer-column col-lg-5 col-md-6 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
						<div class="footer-widget subscribe-widget">
							<h5>Subscribe Newsletter</h5>
							<div class="text">Sign up today for hints, tips and <br> the latest product news</div>
							<!--Emailed Form-->
							<div class="emailed-form">
								<form method="post" action="https://expert-themes.com/html/globex/contact.PHP">
									<div class="form-group">
										<input type="email" name="email" value="" placeholder="Enter Your Email" required>
										<button type="submit" class="theme-btn">Subscribe Now</button>
									</div>
								</form>
							</div>
						</div>
					</div>
					
				</div>
			</div>
			
		</div>
		
		<!-- Footer Bottom -->
		<div class="footer-bottom">
			<div class="auto-container">
				<div class="row clearfix">
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<div class="copyright">Copyright &copy; <?php echo date("Y"); ?> by <a href="https://itechwebnig.com.ng/" style="color: #fff;">Itechnology Group</a> . All Rights Reserved.</div>
					</div>
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<ul class="footer-nav">
								<li><a href="about.PHP">About Us</a></li>
								<li><a href="services.PHP">Services</a></li>
								<li><a href="mission.PHP">Mission</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		
	</footer>
	
	
</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-arrow-up"></span></div>

<script src="js/jquery.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="js/jquery.fancybox.js"></script>
<script src="js/appear.js"></script>
<script src="js/parallax.min.js"></script>
<script src="js/tilt.jquery.min.js"></script>
<script src="js/jquery.paroller.min.js"></script>
<script src="js/owl.js"></script>
<script src="js/wow.js"></script>
<script src="js/nav-tool.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/script.js"></script>
<script src="js/color-settings.js"></script>

</body>
</html>