<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>BASALEH GLOBAL SERVICES LTD</title>
<!-- Stylesheets -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;family=Nunito+Sans:wght@300;600;700;800;900&amp;display=swap" rel="stylesheet">

<!-- Color Switcher Mockup -->
<link href="css/color-switcher-design.css" rel="stylesheet">

<!-- Color Themes -->
<link id="theme-color-file" href="css/color-themes/default-theme.css" rel="stylesheet">

<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
<link rel="icon" href="images/favicon.png" type="image/x-icon">

<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
</head>

<body class="hidden-bar-wrapper">

<div class="page-wrapper">
 	
    <!-- Preloader -->
    <div class="preloader"></div>
 	
 	<!-- Main Header / Header Style Five -->
    <header class="main-header header-style-five">
    
    	<!-- Header Top Four -->
    	<div class="header-top-four">
        	<div class="auto-container">
            	<div class="clearfix">
                    
                    <!--Top Left-->
                    <div class="top-left clearfix">
                    	<ul class="links clearfix">
                        	<li><a href="#"><span class="icon fa fa-phone"></span>(+234) 08038012451</a></li>
                            <li><a href="#"><span class="icon fa fa-envelope"></span>info@gbasalehglobal.ng</a></li>
                            <li><a href="#"><span class="icon fa fa-clock-o"></span>Open Hours 09:00 am - 06:00 pm</a></li>
                        </ul>
                    </div>
                    
                    <!--Top Right-->
                    <div class="top-right clearfix">
                    	<ul class="social-icons">
                            <li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
                            <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                            <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                        </ul>
                       
                    </div>
                    
                </div>
                
            </div>
        </div>
        <!-- Header Top End -->
        
        <!-- Main Box -->
    	<div class="main-box">
        	<div class="auto-container">
            	<div class="outer-container clearfix">
                    <!--Logo Box-->
                    <div class="logo-box">
                        <div class="logo"><a href="https://basalehglobal.com"><img src="images/logo-2.png" alt=""></a></div>
                    </div>
                    
                    <div class="nav-outer clearfix">
					
						<!-- Mobile Navigation Toggler -->
						<div class="mobile-nav-toggler"><span class="icon flaticon-menu-2"></span></div>
						<!-- Main Menu -->
						<nav class="main-menu show navbar-expand-md">
							<div class="navbar-header">
								<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
							</div>
							
							<div class="navbar-collapse collapse clearfix" id="navbarSupportedContent">
								<ul class="navigation clearfix">
									<li class="current"><a href="https://basalehglobal.com">Home</a>
									</li>
									<li class="dropdown"><a href="#">Who We Are</a>
										<ul>
											<li><a href="about.PHP">About Us</a></li>
											<li><a href="team.PHP">Team</a></li>
											<li><a href="mission.PHP">Vision</a></li>
											<li><a href="mission.PHP">Mission</a></li>

										</ul>
									</li>

									<li class="dropdown"><a href="#">Application</a>
										<ul>
											<li><a href="services.PHP">Certificate</a></li>
										</ul>
									</li>
									<li><a href="services.PHP">Services</a></li>

									<li><a href="contact.PHP">Contact us</a></li>
								</ul>
							</div>
						</nav>
                        <!-- Main Menu End-->
                        
                        <!-- Main Menu End-->
                        <div class="outer-box clearfix">
                            
                        </div>
                        
                    </div>
                    <!--Nav Outer End-->
                    
            	</div>    
            </div>
        </div>
        
		<!-- Sticky Header  -->
        <div class="sticky-header">
            <div class="auto-container clearfix">
                <!--Logo-->
                <div class="logo pull-left">
                    <a href="https://basalehglobal.com" title=""><img src="images/logo-2.png" alt="" title=""></a>
                </div>
                <!--Right Col-->
                <div class="pull-right">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav><!-- Main Menu End-->
					
					<!-- Main Menu End-->
					<div class="outer-box clearfix">
					<!-- Nav Btn -->
						<div class="nav-btn navSidebar-button"><span class="icon flaticon-menu"></span></div>
						
					</div>
					
                </div>
            </div>
        </div><!-- End Sticky Menu -->
    
		<!-- Mobile Menu  -->
        <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><span class="icon flaticon-multiply"></span></div>
            
            <nav class="menu-box">
                <div class="nav-logo"><a href="https://basalehglobal.com"><img src="images/logo.png" alt="" title=""></a></div>
                <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
            </nav>
        </div><!-- End Mobile Menu -->
	
    </header>
    <!-- End Main Header -->



    
	
	<!-- Sidebar Cart Item -->
	<div class="xs-sidebar-group info-group">
		<div class="xs-overlay xs-bg-black"></div>
		<div class="xs-sidebar-widget">
			<div class="sidebar-widget-container">
				<div class="widget-heading">
					<a href="#" class="close-side-widget">
						X
					</a>
				</div>
				<div class="sidebar-textwidget">
					
					<!-- Sidebar Info Content -->
					<div class="sidebar-info-contents">
						<div class="content-inner">
							<div class="logo">
								<a href="https://basalehglobal.com"><img src="images/logo-2.png" alt="" /></a>
							</div>
							<div class="content-box wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
								<h2>About Our Company</h2>
								<p class="text">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.</p>
								<a href="contact.PHP" class="theme-btn btn-style-three"><span class="txt">Consultation</span></a>
							</div>
							<div class="contact-info">
								<h2>Contact us</h2>
								<ul class="list-style-one">
									<li><span class="icon fa fa-location-arrow"></span>G6, Barumak Estate, Wuye Abuja</li>
									<li><span class="icon fa fa-phone"></span>(+234)8038012451, 08174212145</li>
									<li><span class="icon fa fa-envelope"></span>basalehglobal@gmail.com</li>
								</ul>
							</div>
							<!-- Social Box -->
							<ul class="social-box">
								<li class="facebook"><a href="#" class="fa fa-facebook-f"></a></li>
								<li class="twitter"><a href="#" class="fa fa-twitter"></a></li>
								<li class="linkedin"><a href="#" class="fa fa-linkedin"></a></li>
								<li class="instagram"><a href="#" class="fa fa-instagram"></a></li>
								<li class="youtube"><a href="#" class="fa fa-youtube"></a></li>
							</ul>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
	<!-- END sidebar widget item -->
	
	<!-- Banner Section Two -->
    <section class="banner-section-two">
		<div class="pattern-layer-one" style="background-image: url(images/main-slider/pattern-4.png)"></div>
		<div class="pattern-layer-two" style="background-image: url(images/main-slider/pattern-5.png)"></div>
		<div class="pattern-layer-three" style="background-image: url(images/main-slider/pattern-6.png)"></div>
		<div class="main-slider-carousel owl-carousel owl-theme">
            
            <div class="slide">
				<div class="auto-container">
					<div class="row clearfix">
						
						<!-- Image Column -->
						<div class="image-column col-lg-6 col-md-12 col-sm-12">
							<div class="inner-column">
								<div class="image">
									<img src="images/main-slider/software_engineering_img1.png" alt="" />
								</div>
							</div>
						</div>
						<!-- Content Column -->
						<div class="content-column col-lg-6 col-md-12 col-sm-12">
							<div class="inner-column">
								<h1>SOFTWARE DEVELOPMENT</h1>
								<div class="text">Beside the hardware and network solutions; with design and development expertise in diverse platforms, best-of-breed tools and techniques,</div>
								<div class="btns-box">
								<a href="detail/software-dev.PHP" class="theme-btn btn-style-one"><span class="txt">Read More</span></a>
							</div>
							</div>
						</div>
						
					</div>
				</div>
			</div>
			
			<div class="slide">
				<div class="auto-container">
					<div class="row clearfix">
						
						<!-- Image Column -->
						<div class="image-column col-lg-6 col-md-12 col-sm-12">
							<div class="inner-column">
								<div class="image">
									<img src="images/main-slider/services-computer.png" alt="" />
								</div>
							</div>
						</div>
						
						<!-- Content Column -->
						<div class="content-column col-lg-6 col-md-12 col-sm-12">
							<div class="inner-column">
								<h1>NETWORK & INFRASTRUCTURE SERVICES</h1>
								<div class="text">BASALEH GLOBAL SERVICES LIMITED's services enable clients to identify, develop, and implement the best-fit solutions that are equipped to meet their changing business requirements.</div>
								<div class="btns-box">
								<a href="detail/network-infa.PHP" class="theme-btn btn-style-one"><span class="txt">Learn More</span></a>
							</div>
							</div>
						</div>
						
					</div>
				</div>
			</div>
			
			<div class="slide">
				<div class="auto-container">
					<div class="row clearfix">
						
						<!-- Image Column -->
						<div class="image-column col-lg-6 col-md-12 col-sm-12">
							<div class="inner-column">
								<div class="image">
									<img src="images/main-slider/Hardware Services_PG.png" alt="" />
								</div>
							</div>
						</div>
						
						<!-- Content Column -->
						<div class="content-column col-lg-6 col-md-12 col-sm-12">
							<div class="inner-column">
								<h1>HARDWARE SALES & SUPPORT SERVICES</h1>
								<div class="text">We offer servers, computers, computer accessories and services by sourcing from local market and from international market as well. Our team of experts is ready to serve you when you are worried due to lack of confidence in “commitment of service”.</div>
								<div class="btns-box">
								<a href="detail/hardware-sales.PHP" class="theme-btn btn-style-one"><span class="txt">Learn More</span></a>
							</div>
							</div>
						</div>
						
					</div>
				</div>
			</div>
			
		</div>
	</section>
	<!-- End Banner Section Two -->
			
<!-- News Section Three -->
	<section class="news-section-three" style="background-image: url(images/background/pattern-9.png)">
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title centered">
				<div class="et_pb_text title">OUR SERVICES</div>
				<h2>We run all kinds of services in form of <br> Information & Technologies</h2>
			</div>
			<div class="three-item-carousel owl-carousel owl-theme">
				
				<!-- News Block Three -->
				<div class="news-block-three">
					<div class="inner-box">
						<div class="image">
							<a href="detail/ict-consultant.PHP"><img src="images/services/2.png" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-design"></span>
								</div>
								<h4><a href="detail/ict-consultant.PHP">ICT CONSULTANCY</a></h4>
								<div class="text">We consult for high-end technology implementation at clients’ site or implementation of new technology according to the clients’</div>
								<a class="read-more" href="detail/ict-consultant.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				
				<!-- News Block Three -->
				<div class="news-block-three">
					<div class="inner-box">
						<div class="image">
							<a href="detail/software-dev.PHP"><img src="images/services/4.jpg" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-coding-2"></span>
								</div>
								<h4><a href="detail/software-dev.PHP">SOFTWARE DEVELOPMENT</a></h4>
								<div class="text">Beside the hardware and network solutions; with design and development expertise in diverse platforms,</div>
								<a class="read-more" href="detail/software-dev.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				
				<!-- News Block Three -->
				<div class="news-block-three">
					<div class="inner-box">
						<div class="image">
							<a href="news-detail.PHP"><img src="images/services/5.jpg" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-network-1"></span>
								</div>
								<h4><a href="news-detail.PHP">NETWORK & INFRASTRUCTURE SERVICES</a></h4>
								<div class="text">BASALEH GLOBAL SERVICES LIMITED's services enable clients to identify, develop, and implement the best-fit solutions</div>
								<a class="read-more" href="news-detail.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				
				<!-- News Block Three -->
				<div class="news-block-three">
					<div class="inner-box">
						<div class="image">
							<a href="news-detail.PHP"><img src="images/services/6.jpg" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-computer"></span>
								</div>
								<h4><a href="news-detail.PHP">HARDWARE SALES & SUPPORT SERVICES</a></h4>
								<div class="text">We offer servers, computers, computer accessories and services by sourcing from local market</div>
								<a class="read-more" href="news-detail.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
			
			</div>
		</div>
	</section>
	<!-- End News Section Three -->
	
	<!-- Counter Section
	<section class="counter-section">
		<div class="auto-container">
			<div class="inner-container">
				Fact Counter 
				<div class="fact-counter">
					<div class="row clearfix">

						 Column 
						<div class="column counter-column col-lg-3 col-md-6 col-sm-12">
							<div class="inner wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
								<div class="content">
									<div class="count-outer count-box">
										<span class="count-text" data-speed="3000" data-stop="330">0</span>+
									</div>
									<h4 class="counter-title">ACTIVE CLIENTS</h4>
								</div>
							</div>
						</div>

						
						<div class="column counter-column col-lg-3 col-md-6 col-sm-12">
							<div class="inner wow fadeInLeft" data-wow-delay="300ms" data-wow-duration="1500ms">
								<div class="content">
									<div class="count-outer count-box alternate">
										<span class="count-text" data-speed="5000" data-stop="850">0</span>+
									</div>
									<h4 class="counter-title">PROJECTS DONE</h4>
								</div>
							</div>
						</div>

					
						<div class="column counter-column col-lg-3 col-md-6 col-sm-12">
							<div class="inner wow fadeInLeft" data-wow-delay="600ms" data-wow-duration="1500ms">
								<div class="content">
									<div class="count-outer count-box">
										<span class="count-text" data-speed="2000" data-stop="25">0</span>+
									</div>
									<h4 class="counter-title">TEAM ADVISORS</h4>
								</div>
							</div>
						</div>

						<div class="column counter-column col-lg-3 col-md-6 col-sm-12">
							<div class="inner wow fadeInLeft" data-wow-delay="900ms" data-wow-duration="1500ms">
								<div class="content">
									<div class="count-outer count-box">
										<span class="count-text" data-speed="3500" data-stop="10">0</span>+
									</div>
									<h4 class="counter-title">GLORIOUS YEARS</h4>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</section>-->
	<!-- End Counter Section -->
	
	<!-- About Section Two -->
	<br><br>
	<section class="about-section-two" style="background-image: url(images/background/3.jpg)">
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- Image Column -->
				<div class="image-column col-lg-7 col-md-12 col-sm-12">
					<div class="inner-column">
						<div class="circle-layer" style="background-image: url(images/background/pattern-10.png)"></div>
						<div class="image">
							<img src="images/resource/about-5.jpg" alt="" />
						</div>
					</div>
				</div>
				
				<!-- Skill Column -->
				<div class="skill-column col-lg-5 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<!-- Sec Title -->
						<div class="sec-title light wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
							<h3 style="color: #ffffff; font-style: italic;">ABOUT BASALEH GLOBAL SERVICES LIMITED</h3>
							<div class="text">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT. 
								<br><p>Since its inception BASALEH GLOBAL SERVICES LIMITED has maintained good record in quality service and time delivery in Consultancy services Supply and Installation, hardware/Software and network solution.</p></div>
						</div>
						<a href="about.PHP" class="theme-btn btn-style-two"><span class="txt">Learn More</span></a>
						
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- End About Section Two -->
	
	
	
	<!-- Process Section -->
    <section class="process-section">
		<div class="pattern-layer-one" style="background-image: url(images/background/pattern-11.jpg)"></div>
		<div class="pattern-layer-two" style="background-image: url(images/background/pattern-12.jpg)"></div>
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title centered">
				<h2 style="color: #ff0000">AREAS OF EXPERTISE</h2>
				<h5 class="wow zoomIn" data-wow-delay="0ms" data-wow-duration="1500ms">Main Strength of <b style="font-style: italic;">BASALEH GLOBAL SERVICES LIMITED</b> lies in <br>the blend of professionals, specialized and highly focused operation.</h5>
			</div>
			<div class="row clearfix">

				<!-- Process Block -->
				<div class="process-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box  wow rollIn" data-wow-delay="0ms" data-wow-duration="1500ms">
					<div class="number-box2"></div>
					<div class="text">
					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> System analysis </li>
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Business process reengineering </li>
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Process development localization</li> 
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Customized and target oriented Workflow design 
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Specialization in Client / Server and Internet / Intranet application and technologies</li> 
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Automation of Financial Institutions, Telco-Operators, Electronic Medias & Business Institutions with the latest development.</li> 
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Customized software development as ancillary product for deployed international software</li> 
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> International software deployment - product development localization 
 					Network Monitoring/ Network Management Support</li>
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Network Monitoring/ Network Management Support</li> 
 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Network, Security & Threat Management Solution</li>
					</div>
						<a class="read-more" href="services-detail.PHP"><span class="arrow flaticon-long-arrow-pointing-to-the-right"></span>Read More</a>
					</div>
				</div>
				
				<!-- Process Block -->
				<div class="process-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow flipInY" data-wow-delay="3ms" data-wow-duration="1500ms">
						<div class="number-box2"></div>
						<div class="text">
						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> 2G/3G/4G/LTe RF Design</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> RF Coverage Simulation Plot</li> 
						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Desktop maintenance and support </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Server maintenance and support </li>
 	 					<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Production operations </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Disaster Recovery and Storage Management Solution </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Power Solution. </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Enterprise-grade LAN Cabling.</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Infrastructure Management Solution.</li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Data Centre Operations and Service Delivery.</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Systems Integration </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Project Management. </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Project support </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Web based support & solution development</li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> E-business solutions </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Data conversion & data entry</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Overall automation consultancy </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Enterprise Server & Storage Solution</li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Disaster Recovery Plan </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Tetra Radio Terminal Programming </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> GIS Servers </li>
 					<li></li>	
						</div>
						<a class="read-more" href="services-detail.PHP"><span class="arrow flaticon-long-arrow-pointing-to-the-right"></span>Read More</a>
					</div>
				</div>
				
				<!-- Process Block -->
				<div class="process-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box  wow rollIn" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="number-box2"></div>
						<div class="text">
						<ul class="price-list">
						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> RF Optimization </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> RF Frequency Planning</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Traffic Modelling </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Antenna System Design</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> In-Building Solutions</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Fleet-mapping and Management</li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Backbone Transmission Design </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Secure Mobile Virtual Network Operator (SMVNO)</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> TETRA over LTe solutions </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Power Generators</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Coverage on Wheel</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Network Monitoring System</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Control Room Solutions</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Systems Integration</li> 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Benchmarking Services</li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Enterprise Server & Storage Solution</li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Disaster Recovery Plan </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Tetra Radio Terminal Programming </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> GIS Servers </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Voice Recording and Playback Solutions 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Inter System Connectivity </li>
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Voice Recording and Playback Solutions 
 						<li><i class="fa fa-arrow-right" style="color: #ff0000;"></i> Inter System Connectivity </li>
						</div>
						<a class="read-more" href="services-detail.PHP"><span class="arrow flaticon-long-arrow-pointing-to-the-right"></span>Read More</a>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- End Process Section -->
	
	<!-- Team Section Two -->
	<!-- Technology Section -->
	<section class="technology-section style-two" style="background-image: url(images/background/1.jpg)">
		<div class="pattern-layer-one" style="background-image: url(images/background/pattern-5.png)"></div>
		<div class="pattern-layer-two" style="background-image: url(images/background/pattern-6.png)"></div>
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title wow fadeInRight" data-wow-delay="0ms" data-wow-duration="1500ms">
				<div class="clearfix">
					<div class="pull-left">
						<div style="color: #ffffff" class="title">OUR DEDICATED TEAM</div>
						<h2 style="color: #ffffff">We have Large No <br> of Expert Team Member</h2>
					</div>
					<div class="pull-right">
						<div style="color: #ffffff" class="text">Our goal is to help our companies maintain or achieve best- in-class <br> positions in their respective industries and our team works.</div>
					</div>
				</div>
			</div>
			<div class="row clearfix">
				
				<!-- Team Block -->
				<div class="team-block-two col-lg-3 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="team.PHP"><img src="images/teams/team-2.jpg" alt="ISMAILA MUHAMMAD" /></a>
						</div>
						<div class="lower-box">
							<!-- Social Box -->
							<ul class="social-box">
								<li><a href="#" class="fa fa-facebook-f"></a></li>
								<li><a href="#" class="fa fa-twitter"></a></li>
								<li><a href="#" class="fa fa-dribbble"></a></li>
							</ul>
							<div class="content">
								<h5><a href="team.PHP">ISMAILA MUHAMMAD</a></h5>
								<div class="designation"><strong>CHAIRMAN</strong> <br>Basaleh Global Services Ltd</div>
							</div>
						</div>
					</div>
				</div>
				
				<!-- Team Block -->
				<div class="team-block-two col-lg-3 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="team.PHP"><img src="images/teams/team-3.jpg" alt="IBRAHIM BABATUDE" /></a>
						</div>
						<div class="lower-box">
							<!-- Social Box -->
							<ul class="social-box">
								<li><a href="#" class="fa fa-facebook-f"></a></li>
								<li><a href="#" class="fa fa-twitter"></a></li>
								<li><a href="#" class="fa fa-dribbble"></a></li>
							</ul>
							<div class="content">
								<h5><a href="team.PHP">IBRAHIM BABATUDE</a></h5>
								<div class="designation"><strong>CEO/MD</strong><br>Basaleh Global Services Ltd</div>
							</div>
						</div>
					</div>
				</div>
				
				<!-- Team Block -->
				<div class="team-block-two col-lg-3 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="team.PHP"><img src="images/teams/team-1.jpg" alt="Dr. Abdullahi Muhammad Basir" /></a>
						</div>
						<div class="lower-box">
							<!-- Social Box -->
							<ul class="social-box">
								<li><a href="#" class="fa fa-facebook-f"></a></li>
								<li><a href="#" class="fa fa-twitter"></a></li>
								<li><a href="#" class="fa fa-dribbble"></a></li>
							</ul>
							<div class="content">
								<h5><a href="team.PHP">Dr. A.M. BASIR</a></h5>
								<div class="designation"><strong>DIRECTOR</strong><br>Basaleh Global Services Ltd</div>
							</div>
						</div>
					</div>
				</div>
				
				<!-- Team Block -->
				<div class="team-block-two col-lg-3 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="team.PHP"><img src="images/teams/team-2.jpg" alt="" /></a>
						</div>
						<div class="lower-box">
							
							<ul class="social-box">
								<li><a href="#" class="fa fa-facebook-f"></a></li>
								<li><a href="#" class="fa fa-twitter"></a></li>
								<li><a href="#" class="fa fa-dribbble"></a></li>
							</ul>
							<div class="content">
								<h5><a href="team.PHP">ISMAILA MUHAMMAD</a></h5>
								<div class="designation"><strong>CHAIRMAN</strong><br>Basaleh Global Services Ltd</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- End Team Section Two -->
	
	<!-- Appointment Section
	<section class="appointment-section">
		<div class="image-layer" style="background-image: url(images/background/4.jpg)"></div>
		<div class="auto-container">
			<div class="sec-title light centered">
				<div class="title">CONTACT US</div>
				<h2>Join Us To Get IT Free <br> Consultations</h2>
			</div>
			<div class="inner-container">
				<div class="row clearfix">
					
					<div class="image-column col-lg-6 col-md-12 col-sm-12">
						<div class="inner-column">
							<div class="image">
								<img src="images/resource/appointment.jpg" alt="" />
							</div>
						</div>
					</div>
					<div class="form-column col-lg-6 col-md-12 col-sm-12">
						<div class="inner-column">
							<h4>You Don't Hesitate To Contact <br> With Us, Now Say Hello......</h4>
							<div class="appointment-form">
								<form method="post" action="https://expert-themes.com/html/globex/appointment.PHP">
									<div class="row clearfix">
										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="text" name="username" placeholder="Name" required="">
											<span class="icon fa fa-user"></span>
										</div>
										
										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="email" name="email" placeholder="Email" required="">
											<span class="icon fa fa-envelope"></span>
										</div>

										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="tel" name="phone" placeholder="Phone No" required="">
											<span class="icon fa fa-phone"></span>
										</div>

										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="text" name="department" placeholder="Department" required="">
											<span class="icon fa fa-home"></span>
										</div>

										<div class="col-lg-12 col-md-12 col-sm-12 form-group">
											<textarea name="message" placeholder="Message"></textarea>
										</div>

										<div class="col-lg-12 col-md-12 col-sm-12 form-group">
											<button class="theme-btn btn-style-three" type="submit" name="submit-form"><span class="txt">Send Massage</span></button>
										</div>
									</div>
								</form>
							</div>
							
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</section>
<!--Sponsors Section-->
	<section class="sponsors-section style-two">
		<div class="auto-container">
			
			<div class="carousel-outer">
                <!--Sponsors Slider-->
                <ul class="sponsors-carousel owl-carousel owl-theme">
                    <li><div class="image-box"><a href="#"><img src="images/clients/1.png" alt=""></a></div></li>
                    <li><div class="image-box"><a href="#"><img src="images/clients/2.png" alt=""></a></div></li>
                    <li><div class="image-box"><a href="#"><img src="images/clients/3.png" alt=""></a></div></li>
                    <li><div class="image-box"><a href="#"><img src="images/clients/4.png" alt=""></a></div></li>
					<li><div class="image-box"><a href="#"><img src="images/clients/1.png" alt=""></a></div></li>
                    <li><div class="image-box"><a href="#"><img src="images/clients/2.png" alt=""></a></div></li>
                    <li><div class="image-box"><a href="#"><img src="images/clients/3.png" alt=""></a></div></li>
                    <li><div class="image-box"><a href="#"><img src="images/clients/4.png" alt=""></a></div></li>
                </ul>
            </div>
			
		</div>
	</section>
	<!--End Sponsors Section-->
	
	<!-- Main Footer -->
    <footer class="main-footer style-two">
		<div class="pattern-layer-one" style="background-image: url(images/background/pattern-7.png)"></div>
		<div class="pattern-layer-two" style="background-image: url(images/background/pattern-8.png)"></div>
		<!--Waves end-->
    	<div class="auto-container">
        	<!--Widgets Section-->
            <div class="widgets-section">
            	<div class="row clearfix">
                	
                    <!-- Column -->
                    <div class="big-column col-lg-6 col-md-12 col-sm-12">
						<div class="row clearfix">
						
                        	<!-- Footer Column -->
                            <div class="footer-column col-lg-7 col-md-6 col-sm-12">
                                <div class="footer-widget logo-widget">
									<div class="logo">
										<a href="https://basalehglobal.com"><img src="images/logo-2.png" alt="" /></a>
									</div>
									<div class="text wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.</div>
									<!-- Social Box -->
									<ul class="social-box">
										<li><a href="#" class="fa fa-facebook-f"></a></li>
										<li><a href="#" class="fa fa-linkedin"></a></li>
										<li><a href="#" class="fa fa-twitter"></a></li>
										<li><a href="#" class="fa fa-google"></a></li>
									</ul>
								</div>
							</div>
							
							<!-- Footer Column -->
                            <div class="footer-column col-lg-5 col-md-6 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
                                <div class="footer-widget links-widget">
									<h5>Quick Links</h5>
									<ul class="list-link">
										<li><a href="#">Software Development Services</a></li>
										<li><a href="#">Hardware Sales</a></li>
										<li><a href="#">IT support & helpdesk</a></li>
										<li><a href="#">Secure Communications Design</a></li>
										<li><a href="#">Custom Software</a></li>
										<li><a href="#">ICT Consultation</a></li>
										<li><a href="#">E-business solutions</a></li>
									</ul>
								</div>
							</div>
							
						</div>
					</div>
					
					<!-- Column -->
                    <div class="big-column col-lg-6 col-md-12 col-sm-12">
						<div class="row clearfix">
							
							<!-- Footer Column -->
							<div class="footer-column col-lg-6 col-md-6 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
								<div class="footer-widget links-widget">
									<br><br><br>
									<ul class="list-link">
										<li><a href="#">Software Development Services</a></li>
										<li><a href="#">Hardware Sales</a></li>
										<li><a href="#">IT support & helpdesk</a></li>
										<li><a href="#">Secure Communications Design</a></li>
										<li><a href="#">Custom Software</a></li>
										<li><a href="#">ICT Consultation</a></li>
										<li><a href="#">E-business solutions</a></li>
									</ul>
								</div>
							</div>
							
							<!-- Footer Column -->
							<div class="footer-column col-lg-6 col-md-6 col-sm-12">
								<div class="footer-widget contact-widget">
									<h5>Contact Us</h5>
									<ul>
										<li>
											<span class="icon flaticon-placeholder-2"></span>
											<strong>Address</strong>
											G6, Barumak Estate, Wuye Abuja.
										</li>
										<li>
											<span class="icon flaticon-phone-call"></span>
											<strong>Phone</strong>
											<a href="tel:+234-803-8012-451">+234 08038012451, 08174212145</a>
										</li>
										<li>
											<span class="icon flaticon-email-1"></span>
											<strong>E-Mail</strong>
											<a href="mailto:info@basalehglobal.ng">info@basalehglobal.ng</a>
										</li>
									</ul>
								</div>
							</div>
							
						</div>
					</div>
					
				</div>
			</div>
			
			<!-- Footer Bottom -->
			<div class="footer-bottom">
				<div class="auto-container">
					<div class="row clearfix">
						<!-- Column -->
						<div class="column col-lg-6 col-md-12 col-sm-12">
						<div class="copyright">Copyright &copy; <?php echo date("Y"); ?> by <a href="https://itechwebnig.com.ng/" style="color: #fff;">Itechnology Group</a> . All Rights Reserved.</div>
					</div>
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<ul class="footer-nav">
								<li><a href="about.PHP">About Us</a></li>
								<li><a href="services.PHP">Services</a></li>
								<li><a href="mission.PHP">Mission</a></li>
						</ul>
					</div>
					</div>
				</div>
			</div>
			
		</div>
	</footer>
	
	
</div>
<!--End pagewrapper-->





<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-arrow-up"></span></div>

<script src="js/jquery.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="js/jquery.fancybox.js"></script>
<script src="js/appear.js"></script>
<script src="js/parallax.min.js"></script>
<script src="js/tilt.jquery.min.js"></script>
<script src="js/jquery.paroller.min.js"></script>
<script src="js/owl.js"></script>
<script src="js/wow.js"></script>
<script src="js/nav-tool.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/script.js"></script>
<script src="js/custom.min.js"></script>

</body>
</html>