<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>BASALEH GLOBAL SERVICES LTD | Services</title>
<!-- Stylesheets -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;family=Nunito+Sans:wght@300;600;700;800;900&amp;display=swap" rel="stylesheet">

<!-- Color Switcher Mockup -->
<link href="css/color-switcher-design.css" rel="stylesheet">

<!-- Color Themes -->
<link id="theme-color-file" href="css/color-themes/default-theme.css" rel="stylesheet">

<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
<link rel="icon" href="images/favicon.png" type="image/x-icon">

<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
</head>

<body class="hidden-bar-wrapper">

<div class="page-wrapper">
 	
    <!-- Preloader -->
    <div class="preloader"></div>
 	
 	<!-- Main Header-->
    <header class="main-header header-style-one">
    	
		<!-- Header Top -->
        <div class="header-top">
            <div class="auto-container">
                <div class="clearfix">
					<!-- Top Left -->
					<div class="top-left">
						<!-- Info List -->
						<ul class="info-list">
							<li><a href="mailto:info@basalehglobal.ng"><span class="icon flaticon-email"></span> info@basalehglobal.ng</a></li>
							<li><a href="tel:+2348038012451"><span class="icon flaticon-telephone"></span> (+234) 08038012451, 08174212145</a></li>
						</ul>
					</div>
					
					<!-- Top Right -->
                    <div class="top-right pull-right">
						<!-- Social Box -->
						<ul class="social-box">
							<li><a href="#" class="fa fa-facebook-f"></a></li>
							<li><a href="#" class="fa fa-twitter"></a></li>
							<li><a href="#" class="fa fa-dribbble"></a></li>
							<li><a href="#" class="fa fa-google"></a></li>
						</ul>
                    </div>
					
                </div>
            </div>
        </div>
		
		<!--Header-Upper-->
        <div class="header-upper">
        	<div class="auto-container clearfix">
            	
				<div class="pull-left logo-box">
					<div class="logo"><a href="http://basalehglobal.com"><img src="images/logo-2.png" alt="" title=""></a></div>
				</div>
				
				<div class="nav-outer clearfix">
					<!--Mobile Navigation Toggler-->
					<div class="mobile-nav-toggler"><span class="icon flaticon-menu"></span></div>
					<!-- Main Menu -->
					<nav class="main-menu navbar-expand-md">
						<div class="navbar-header">
							<!-- Toggle Button -->    	
							<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						
						<div class="navbar-collapse collapse clearfix" id="navbarSupportedContent">
							<ul class="navigation clearfix">
								<li><a href="https://basalehglobal.com">Home</a></li>
								
								<li class="dropdown"><a href="#">Who We Are</a>
										<ul>
											<li><a href="about.PHP">About Us</a></li>
											<li><a href="team.PHP">Team</a></li>
											<li><a href="mission.PHP">Vision</a></li>
											<li><a href="mission.PHP">Mission</a></li>

										</ul>
									</li>

									<li class="dropdown"><a href="#">Application</a>
										<ul>
											<li><a href="services.PHP">Certificate</a></li>
										</ul>
									</li>

								<li class="current"><a href="services.PHP">Services</a></li>
								
								<li><a href="contact.PHP">Contact us</a></li>
							</ul>
						</div>
					</nav>
					
					<!-- Main Menu End-->
					<div class="outer-box clearfix">
					
						
						<!-- Nav Btn -->
						<div class="nav-btn navSidebar-button"><span class="icon flaticon-menu-2"></span></div>
						
						
							
					</div>
				</div>
				
            </div>
        </div>
        <!--End Header Upper-->
        
		<!-- Sticky Header  -->
        <div class="sticky-header">
            <div class="auto-container clearfix">
                <!--Logo-->
                <div class="logo pull-left">
                    <a href="http://basalehglobal.com" title=""><img src="images/logo-2.png" alt="" title=""></a>
                </div>
                <!--Right Col-->
                <div class="pull-right">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav><!-- Main Menu End-->
					
					<!-- Main Menu End-->
					<div class="outer-box clearfix">
					
						<!-- Nav Btn -->
						<div class="nav-btn navSidebar-button"><span class="icon flaticon-menu"></span></div>
						
					</div>
					
                </div>
            </div>
        </div><!-- End Sticky Menu -->
    
		<!-- Mobile Menu  -->
        <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><span class="icon flaticon-multiply"></span></div>
            
            <nav class="menu-box">
                <div class="nav-logo"><a href="http://basalehglobal.com"><img src="images/logo.png" alt="" title=""></a></div>
                <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
            </nav>
        </div><!-- End Mobile Menu -->
	
    </header>
    <!-- End Main Header -->
	
	<!-- Sidebar Cart Item -->
	<div class="xs-sidebar-group info-group">
		<div class="xs-overlay xs-bg-black"></div>
		<div class="xs-sidebar-widget">
			<div class="sidebar-widget-container">
				<div class="widget-heading">
					<a href="#" class="close-side-widget">
						X
					</a>
				</div>
				<div class="sidebar-textwidget">
					
					<!-- Sidebar Info Content -->
					<div class="sidebar-info-contents">
						<div class="content-inner">
							<div class="logo">
								<a href="http://basalehglobal.com"><img src="images/logo-2.png" alt="" /></a>
							</div>
							<div class="content-box">
								<h2>About Our Company</h2>
								<p class="text">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.</p>
								<a href="contact.PHP" class="theme-btn btn-style-three"><span class="txt">Consultation</span></a>
							</div>
							<div class="contact-info">
								<h2>Contact us</h2>
								<ul class="list-style-one">
									<li><span class="icon fa fa-location-arrow"></span>G6, Barumak Estate, Wuye Abuja</li>
									<li><span class="icon fa fa-phone"></span>(+234)8038012451, 08174212145</li>
									<li><span class="icon fa fa-envelope"></span>basalehglobal@gmail.com</li>
								</ul>
							</div>
							<!-- Social Box -->
							<ul class="social-box">
								<li class="facebook"><a href="#" class="fa fa-facebook-f"></a></li>
								<li class="twitter"><a href="#" class="fa fa-twitter"></a></li>
								<li class="linkedin"><a href="#" class="fa fa-linkedin"></a></li>
								<li class="instagram"><a href="#" class="fa fa-instagram"></a></li>
								<li class="youtube"><a href="#" class="fa fa-youtube"></a></li>
							</ul>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
	<!-- END sidebar widget item -->
	
	<!--Page Title-->
    <section class="page-title">
		<div class="pattern-layer-one" style="background-image: url(images/background/pattern-16.png)"></div>
    	<div class="auto-container">
			<h2>Services</h2>
			<ul class="page-breadcrumb">
				<li><a href="http://basalehglobal.com">home</a></li>
				<li>Services</li>
			</ul>
        </div>
    </section>
    <!--End Page Title-->


    
	
	<!-- Services Page Section -->
	<section class="services-page-section">
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- News Block Three -->
				<div class="news-block-three col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="detail/software-dev.PHP"><img src="images/main-slider/software_engineering_img1.png" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-coding-1"></span>
								</div>
								<h4><a href="detail/software-dev.PHP">SOFTWARE DEVELOPEMT</a></h4>
								<div class="text">Beside the hardware and network solutions; with design and development expertise in diverse platforms, best-of-breed tools and techniques,</div>
								<a class="read-more" href="detail/software-dev.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				
				<!-- News Block Three -->
				<div class="news-block-three style-two col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="detail/network-infa.PHP"><img src="images/services/services-computer.png" class="img-responsive"></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
								<span class="icon flaticon-human-resources"></span>
								</div><br>
								<h4><a href="detail/network-infa.PHP">NETWORK & INFRASTRUCTURE</a></h4>
								<div class="text">BASALEH GLOBAL SERVICES LIMITED's services enable clients to identify, develop, and implement the best-fit solutions</div>
								<a class="read-more" href="detail/network-infa.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>

					</div>
				</div>
				
				<!-- News Block Three -->
				<div class="news-block-three col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="detail/hardware-sales.PHP"><img src="images/services/Hardware Services_PG.png" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-computer"></span>
								</div>
								<h4><a href="detail/hardware-sales.PHP">HARDWARE SALES & SUPPORT SERVICES</a></h4>
								<div class="text">We offer servers, computers, computer accessories and services by sourcing from local market and from international market as well.</div>
								<a class="read-more" href="detail/hardware-sales.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				
				<!-- News Block Three -->
				<div class="news-block-three col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="detail/ict-consultant.PHP"><img src="images/services/ICT Consultant.png" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-monitor-2"></span>
								</div>
								<h4><a href="detail/ict-consultant.PHP">ICT CONSULTANCY</a></h4>
								<div class="text">We consult for high-end technology implementation at clients’ site or implementation of new technology according to the clients’</div>
								<a class="read-more" href="detail/ict-consultant.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				
				<?php /*?><!-- News Block Three -->
				<div class="news-block-three col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="services-detail.PHP"><img src="images/resource/news-12.jpg" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-monitor-2"></span>
								</div>
								<h4><a href="services-detail.PHP">IT Consultancy</a></h4>
								<div class="text">Turn to our experts to perform comprehensive, multi-stage testing and auditing of your software.</div>
								<a class="read-more" href="services-detail.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				
				<!-- News Block Three -->
				<div class="news-block-three col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box">
						<div class="image">
							<a href="services-detail.PHP"><img src="images/resource/news-13.jpg" alt="" /></a>
						</div>
						<div class="lower-content">
							<div class="content">
								<div class="icon-box">
									<span class="icon flaticon-human-resources"></span>
								</div>
								<h4><a href="services-detail.PHP">Dedicated Team</a></h4>
								<div class="text">Over the past decade, our customers succeeded by leveraging Intellectsoft’s process of building, motivating.</div>
								<a class="read-more" href="services-detail.PHP">Read More<span class="arrow flaticon-long-arrow-pointing-to-the-right"></span></a>
							</div>
						</div>
					</div>
				</div><?php */?>
				
			</div>
		</div>
	</section>
	<!-- End Services Page Section -->
	
	<!-- Featured Section -->
	<br/><br><br/><br><br/><br>
	<!-- Services Section Two -->
	<section class="services-section-two margin-top">
		<div class="auto-container">
			<div class="upper-box">
				<div class="icon-one" style="background-image: url(images/icons/icon-1.png)"></div>
				<div class="icon-two" style="background-image: url(images/icons/icon-2.png)"></div>
				<div class="icon-three" style="background-image: url(images/icons/icon-3.png)"></div>
				<!-- Sec Title -->
				<div class="sec-title light centered">
					<div class="title">AREAS OF EXPERTISE</div>
					<h2>Main Strength of BASALEH GLOBAL SERVICES LIMITED<br> lies in the blend of professionals, specialized<br> and highly focused operation.</h2>
				</div>
			</div>
			<div class="inner-container">
				<div class="row clearfix">
					
					<!-- Service Block Two -->
					<div class="service-block-two col-lg-4 col-md-6 col-sm-12">
						<div class="inner-box wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
							<div class="shape-one"></div>
							<div class="shape-two"></div>
							<div class="icon-box">
								<span class="icon flaticon-coding-1"></span>
							</div>
							<h5><a></a></h5>
							<ul class="text">
							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>System analysis </li>

 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Business process reengineering </li>

 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Process development localization </li>

 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Customized and target oriented Workflow design </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Specialization in Client / Server and Internet / Intranet a<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>pplication and technologies </li>

 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Automation of Financial Institutions, Telco-Operators, Electronic Medias & Business Institutions with the latest development. </li>

 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Customized software development as ancillary product for deployed international software </li>

 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>International software deployment - product development localization </li>

 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i> Network Monitoring/ Network Management Support 
 							Network, Security & Threat Management Solution </li>
							</ul>
						</div>
					</div>
					


					<!-- Service Block Two -->
					<div class="service-block-two col-lg-4 col-md-6 col-sm-12">
						<div class="inner-box wow fadeInRight" data-wow-delay="0ms" data-wow-duration="1500ms">
							<div class="shape-one"></div>
							<div class="shape-two"></div>
							<div class="icon-box">
								<span class="icon flaticon-computer"></span>
							</div>
							<h5></h5>
							<ul class="text">
							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Desktop maintenance and support  </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Server maintenance and support </li>
 	 						
 	 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Production operations </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Disaster Recovery and Storage Management Solution </li> 
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Power Solution. </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Enterprise-grade LAN Cabling. </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Infrastructure Management Solution. </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Data Centre Operations and Service Delivery. </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Systems Integration  </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Project Management. </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Project support </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Web based support & solution development </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>E-business solutions </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Data conversion & data entry </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Overall automation consultancy </li>
 							
 							<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>Enterprise Server & Storage Solution </li>
							</ul>
						</div>
					</div>

					<!-- Service Block Two -->
					<div class="service-block-two col-lg-4 col-md-6 col-sm-12">
						<div class="inner-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
							<div class="shape-one"></div>
							<div class="shape-two"></div>
							<div class="icon-box">
								<span class="icon flaticon-human-resources"></span>
							</div>
							<h5><a></a></h5>
							<ul class="text">
						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>  2G/3G/4G/LTe RF Design
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	RF Coverage Simulation Plot
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	RF Optimization 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	RF Frequency Planning 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Traffic Modelling 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Antenna System Design 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	In-Building Solutions 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Fleet-mapping and Management 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Backbone Transmission Design 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Secure Mobile Virtual Network Operator (SMVNO) 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	TETRA over LTe solutions 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Disaster Recovery Plan 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Tetra Radio Terminal Programming 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	GIS Servers 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Voice Recording and Playback Solutions 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Inter System Connectivity 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Power Generators 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Coverage on Wheel 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Network Monitoring System 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Control Room Solutions 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Systems Integration 
 						<li><i class="fa fa-arrow-right" style="font-size: 10px; color: red"></i>	Benchmarking Services </li>

							</ul>
						</div>
					</div>
					
					





					
					<!-- Service Block Two -->
					<div class="service-block-two col-lg-4 col-md-6 col-sm-12">
						<div class="inner-box wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
							<div class="shape-one"></div>
							<div class="shape-two"></div>
							<div class="icon-box">
								<span class="icon flaticon-web"></span>
							</div>
							<h5><a href="services-detail.PHP">SECURE COMMUNICATIONS DESIGN</a></h5>
							<div class="text">Through the vast experiences by our directors, we provide design and optimization services for public and private mobile network operators throughout the Asia Pacific region. Our main expertise involves design of RF cellular 2G/3G/4G/LTe networks as well as Secure Tetra Networks for Public Security. Apart from commercial local networks;<br><i>
							BASALEH GLOBAL SERVICES LIMITED</i> also specializes in the Design & Commission of Mission Critical Radio Communications for -
							<br>  
 							<ul>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Airport </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Transportation Companies </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Oil & Gas </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Medical Team </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Government Agencies  </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Public Safety </li>
 							</ul>
							</div>
						</div>
					</div>
					
					<!-- Service Block Two -->
					<div class="service-block-two col-lg-4 col-md-6 col-sm-12">
						<div class="inner-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
							<div class="shape-one"></div>
							<div class="shape-two"></div>
							<div class="icon-box">
								<span class="icon flaticon-monitor-2"></span>
							</div>
							<h5></h5>
							<div class="text">
							<ul>
							<li><i class="fa fa-circle" style="font-size: 10px; color: black;"></i> Mobile Switching </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black;"></i> Radio Dispatching </li> 

 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> RF Base Stations </li>
 							
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i>Billing System <li>
 							
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i>TETRA terminals  </li>
 							
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Hybrid System </li> 
 							
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> GIS System </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Voice Recording </li>
 							
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Authentication Servers </li>
 							<li><i class="fa fa-circle" style="font-size: 10px; color: black"></i> Network Monitoring </li>
 						</ul>
							</div>
						</div>
					</div>
					
					<!-- Service Block Two -->
					<div class="service-block-two col-lg-4 col-md-6 col-sm-12">
						<div class="inner-box wow fadeInRight" data-wow-delay="0ms" data-wow-duration="1500ms">
							<div class="shape-one"></div>
							<div class="shape-two"></div>
							<div class="icon-box">
								<span class="icon flaticon-human-resources"></span>
							</div>
							<h5><a href="services-detail.PHP">Dedicated Team</a></h5>
							<div class="text">Over the past decade, our customers succeeded by leveraging Intellectsoft’s process of building, motivating.</div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</section>
	<!-- End Services Section Two -->
	
	<?php /*?><!-- Appointment Section -->
	<section class="appointment-section style-two">
		<div class="image-layer" style="background-image: url(images/background/4.jpg)"></div>
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title light centered">
				<div class="title">CONTACT US</div>
				<h2>Join Us To Get IT Free <br> Consultations</h2>
			</div>
			<div class="inner-container">
				<div class="row clearfix">
					
					<!-- Image Column -->
					<div class="image-column col-lg-6 col-md-12 col-sm-12">
						<div class="inner-column wow slideInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
							<div class="image">
								<img src="images/resource/appointment.jpg" alt="" />
							</div>
						</div>
					</div>
					
					<!-- Form Column -->
					<div class="form-column col-lg-6 col-md-12 col-sm-12">
						<div class="inner-column">
							<h4>You Don't Hesitate To Contact <br> With Us, Now Say Hello......</h4>
							<!-- Appointment Form -->
							<div class="appointment-form">
								<form method="post" action="https://expert-themes.com/html/globex/appointment.PHP">
									<div class="row clearfix">
										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="text" name="username" placeholder="Name" required="">
											<span class="icon fa fa-user"></span>
										</div>
										
										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="email" name="email" placeholder="Email" required="">
											<span class="icon fa fa-envelope"></span>
										</div>

										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="tel" name="phone" placeholder="Phone No" required="">
											<span class="icon fa fa-phone"></span>
										</div>

										<div class="col-lg-6 col-md-6 col-sm-12 form-group">
											<input type="text" name="department" placeholder="Department" required="">
											<span class="icon fa fa-home"></span>
										</div>

										<div class="col-lg-12 col-md-12 col-sm-12 form-group">
											<textarea name="message" placeholder="Message"></textarea>
										</div>

										<div class="col-lg-12 col-md-12 col-sm-12 form-group">
											<button class="theme-btn btn-style-three" type="submit" name="submit-form"><span class="txt">Send Massage</span></button>
										</div>
									</div>
								</form>
							</div>
							
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</section>
	<?php */?>
	
	<!-- Info Section -->
	<section class="info-section" style="background-image: url(images/background/6.jpg)">
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- Logo Column -->
				<div class="logo-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="logo">
							<a href="http://basalehglobal.com"><img src="images/logo-2.png" alt="" /></a>
						</div>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-pin"></span></div>
						<ul>
							<li><strong>Address</strong></li>
							<li>G6, Barumak Estate, Wuye Abuja.</li>
						</ul>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-phone-call"></span></div>
						<ul>
							<li><strong>Phone</strong></li>
							<li>+ (+234) 08038012451, +234 08174212145</li>
						</ul>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-email-1"></span></div>
						<ul>
							<li><strong>E-Mail</strong></li>
							<li>info@basalehglobal.com</li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- End Info Section -->
	
	<!-- Main Footer -->
    <footer class="main-footer style-three">
		<div class="pattern-layer-three" style="background-image: url(images/background/pattern-14.png)"></div>
		<div class="pattern-layer-four" style="background-image: url(images/background/pattern-15.png)"></div>
		<!--Waves end-->
    	<div class="auto-container">
        	<!--Widgets Section-->
            <div class="widgets-section">
            	<div class="row clearfix">
                	
					<!-- Footer Column -->
					<div class="footer-column col-lg-4 col-md-6 col-sm-12">
						<div class="footer-widget logo-widget">
							<h5>About Basaleh</h5>
							<div class="text">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.</div>
						</div>
					</div>
					
					<!-- Footer Column -->
					<div class="footer-column col-lg-3 col-md-6 col-sm-12">
						<div class="footer-widget links-widget">
							<h5>Quick Links</h5>
							<ul class="list-link">
								<li><a href="http://basalehglobal.ng/detail/hardware-sales.PHP">Hardware services</a></li>
								<li><a href="http://basalehglobal.ng/detail/network-infa.PHP">Network infrastructure</a></li>
								<li><a href="http://basalehglobal.ng/detail/software-dev.PHP">Software Development</a></li>
								<li><a href="http://basalehglobal.ng/detail/ict-consultant.PHP">ICT Consultant</a></li>
							</ul>
						</div>
					</div>
					
                    <!-- Footer Column -->
					<div class="footer-column col-lg-5 col-md-6 col-sm-12">
						<div class="footer-widget subscribe-widget">
							<!--Emailed Form-->
							<div class="emailed-form">
								<ul class="list-link">
								<li><a href="#">Managed IT services</a></li>
								<li><a href="#">Cloud Services</a></li>
								<li><a href="#">IT support & helpdesk</a></li>
							</ul>
						</div>
					</div>
					
				</div>
			</div>
			
		</div>
		
		<!-- Footer Bottom -->
		<div class="footer-bottom">
			<div class="auto-container">
				<div class="row clearfix">
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<div class="copyright">Copyright &copy; <?php echo date("Y"); ?> by <a href="https://itechwebnig.com.ng/" style="color: #fff;">Itechnology Group</a> . All Rights Reserved.</div>
					</div>
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<ul class="footer-nav">
								<li><a href="about.PHP">About Us</a></li>
								<li><a href="services.PHP">Services</a></li>
								<li><a href="mission.PHP">Mission</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		
	</footer>
	
	
</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-arrow-up"></span></div>

<script src="js/jquery.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="js/jquery.fancybox.js"></script>
<script src="js/appear.js"></script>
<script src="js/parallax.min.js"></script>
<script src="js/tilt.jquery.min.js"></script>
<script src="js/jquery.paroller.min.js"></script>
<script src="js/owl.js"></script>
<script src="js/wow.js"></script>
<script src="js/nav-tool.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/script.js"></script>
<script src="js/color-settings.js"></script>

</body>
</html>