<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>BASALEH GLOBAL SERVICES LTD | Hardware Sales & Support Services</title>
<!-- Stylesheets -->
<link href="/css/bootstrap.css" rel="stylesheet">
<link href="/css/style.css" rel="stylesheet">
<link href="/css/responsive.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;family=Nunito+Sans:wght@300;600;700;800;900&amp;display=swap" rel="stylesheet">

<!-- Color Switcher Mockup -->
<link href="/css/color-switcher-design.css" rel="stylesheet">

<!-- Color Themes -->
<link id="theme-color-file" href="/css/color-themes/default-theme.css" rel="stylesheet">

<link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon">
<link rel="icon" href="/images/favicon.png" type="image/x-icon">

<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
</head>

<body class="hidden-bar-wrapper">

<div class="page-wrapper">
 	
    <!-- Preloader -->
    <div class="preloader"></div>
 	
 	<!-- Main Header-->
    <header class="main-header header-style-one">
    	
		<!-- Header Top -->
        <div class="header-top">
            <div class="auto-container">
                <div class="clearfix">
					<!-- Top Left -->
					<div class="top-left">
						<!-- Info List -->
						<ul class="info-list">
							<li><a href="mailto:info@basalehglobal.ng"><span class="icon flaticon-email"></span> info@basalehglobal.ng</a></li>
							<li><a href="tel:+2348038012451"><span class="icon flaticon-telephone"></span> (+234) 08038012451, 08174212145</a></li>
						</ul>
					</div>
					
					<!-- Top Right -->
                    <div class="top-right pull-right">
						<!-- Social Box -->
						<ul class="social-box">
							<li><a href="#" class="fa fa-facebook-f"></a></li>
							<li><a href="#" class="fa fa-twitter"></a></li>
							<li><a href="#" class="fa fa-dribbble"></a></li>
							<li><a href="#" class="fa fa-google"></a></li>
						</ul>
                    </div>
					
                </div>
            </div>
        </div>
		
		<!--Header-Upper-->
        <div class="header-upper">
        	<div class="auto-container clearfix">
            	
				<div class="pull-left logo-box">
					<div class="logo"><a href="https://basalehglobal.com"><img src="images/logo-2.png" alt="" title=""></a></div>
				</div>
				
				<div class="nav-outer clearfix">
					<!--Mobile Navigation Toggler-->
					<div class="mobile-nav-toggler"><span class="icon flaticon-menu"></span></div>
					<!-- Main Menu -->
					<nav class="main-menu navbar-expand-md">
						<div class="navbar-header">
							<!-- Toggle Button -->    	
							<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						
						<div class="navbar-collapse collapse clearfix" id="navbarSupportedContent">
							<ul class="navigation clearfix">
								<li><a href="https://basalehglobal.com">Home</a></li>
									<li class="dropdown"><a href="#">Who We Are</a>
										<ul>
											<li><a href="/about.PHP">About Us</a></li>
											<li><a href="/team.PHP">Team</a></li>
											<li><a href="/mission.PHP">Vision</a></li>
											<li><a href="/mission.PHP">Mission</a></li>

										</ul>
									</li>

									<li class="dropdown"><a href="#">Application</a>
										<ul>
											<li><a href="/services.PHP">Certificate</a></li>
										</ul>
									</li>
								<li class="current"><a href="/services.PHP">Services</a>
								</li>
								
								<li><a href="/contact.PHP">Contact us</a></li>
							</ul>
						</div>
					</nav>
					
					<!-- Main Menu End-->
					<div class="outer-box clearfix">
						<!-- Nav Btn -->
						<div class="nav-btn navSidebar-button"><span class="icon flaticon-menu-2"></span></div>
						
							
					</div>
				</div>
				
            </div>
        </div>
        <!--End Header Upper-->
        
		<!-- Sticky Header  -->
        <div class="sticky-header">
            <div class="auto-container clearfix">
                <!--Logo-->
                <div class="logo pull-left">
                    <a href="https://basalehglobal.com" title=""><img src="/images/logo-2.png" alt="" title=""></a>
                </div>
                <!--Right Col-->
                <div class="pull-right">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav><!-- Main Menu End-->
					
					<!-- Main Menu End-->
					<div class="outer-box clearfix">
						
						<!-- Nav Btn -->
						<div class="nav-btn navSidebar-button"><span class="icon flaticon-menu"></span></div>
						
					</div>
					
                </div>
            </div>
        </div><!-- End Sticky Menu -->
    
		<!-- Mobile Menu  -->
        <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><span class="icon flaticon-multiply"></span></div>
            
            <nav class="menu-box">
                <div class="nav-logo"><a href=https://basalehglobal.com"><img src="/images/logo-2.png" alt="" title=""></a></div>
                <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
            </nav>
        </div><!-- End Mobile Menu -->
	
    </header>
    <!-- End Main Header -->
	
	<!-- Sidebar Cart Item -->
	<div class="xs-sidebar-group info-group">
		<div class="xs-overlay xs-bg-black"></div>
		<div class="xs-sidebar-widget">
			<div class="sidebar-widget-container">
				<div class="widget-heading">
					<a href="#" class="close-side-widget">
						X
					</a>
				</div>
				<div class="sidebar-textwidget">
					
					<!-- Sidebar Info Content -->
					<div class="sidebar-info-contents">
						<div class="content-inner">
							<div class="logo">
								<a href=https://basalehglobal.com"><img src="/images/logo-2.png" alt="" /></a>
							</div>
							<div class="content-box">
								<h2>About Our Company</h2>
								<p class="text">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.</p>
								<a href="/contact.PHP" class="theme-btn btn-style-three"><span class="txt">Consultation</span></a>
							</div>
							<div class="contact-info">
								<h2>Contact us</h2>
								<ul class="list-style-one">
									<li><span class="icon fa fa-location-arrow"></span>G6, Barumak Estate, Wuye Abuja</li>
									<li><span class="icon fa fa-phone"></span>(+234)8038012451, 08174212145</li>
									<li><span class="icon fa fa-envelope"></span>basalehglobal@gmail.com</li>
								</ul>
							</div>
							<!-- Social Box -->
							<ul class="social-box">
								<li class="facebook"><a href="#" class="fa fa-facebook-f"></a></li>
								<li class="twitter"><a href="#" class="fa fa-twitter"></a></li>
								<li class="linkedin"><a href="#" class="fa fa-linkedin"></a></li>
								<li class="instagram"><a href="#" class="fa fa-instagram"></a></li>
								<li class="youtube"><a href="#" class="fa fa-youtube"></a></li>
							</ul>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
	<!-- END sidebar widget item -->
	
	<!--Page Title-->
    <section class="page-title">
		<div class="pattern-layer-one" style="background-image: url(/images/background/pattern-16.png)"></div>
    	<div class="auto-container">
			<h2>Hardware Sales Service</h2>
			<ul class="page-breadcrumb">
				<li><a href="https://basalehglobal.com">home</a></li>
				<li>Services</li>
			</ul>
        </div>
    </section>
    <!--End Page Title-->

	<!--Sidebar Page Container-->
    <div class="sidebar-page-container">
    	<div class="auto-container">
        	<div class="row clearfix">
				
				<!-- Sidebar Side -->
                <div class="sidebar-side left-sidebar col-lg-4 col-md-12 col-sm-12">
                	<aside class="sidebar sticky-top">
						
						<!-- Services -->
                        <div class="sidebar-widget">
                            <ul class="service-list">
                                <li style="background-color: #0098DA; font-size: 14px;"><a style="color: #fff;">Delivery & Installation:</a></li>
                                <li><a><span class="arrow fa fa-arrow-right"></span> Data Centre , Structure Cabling Systems</a></li>
                                <li><a><span class="arrow fa fa-arrow-right"></span> CISCO Switch, Firewall, Wireless & Routers.</a></li>
                                <li><a><span class="arrow fa fa-arrow-right"></span> PC, Server & Storage</a></li>
                                <li><a><span class="arrow fa fa-arrow-right"></span> Server & Switch Equipment maintenance</a></li>
                            </ul>
                        </div>
						
						<!-- Contact Widget -->
						<div class="sidebar-widget contact-widget">
							<div class="widget-content" style="background-image:url(/images/resource/service.jpg)">
								<div class="border-layer"></div>
								<div class="icon-box flaticon-phone-call"></div>
								<h4>How Can We Help?</h4>
								<div class="text">If you need any help, please <br> feel free to contact us.</div>
								<ul>
									<li><span class="icon flaticon-call"></span>(+234) 08038012451</li>
									<li><span class="icon flaticon-envelope"></span>info@basaleglobal.ng</li>
								</ul>
							</div>
						</div>
						
					</aside>
				</div>
				
				<!-- Content Side -->
                <div class="content-side right-sidebar col-lg-8 col-md-12 col-sm-12">
                	<div class="services-detail">
						<div class="inner-box">
							<h2>HARDWARE SALES & SUPPORT SERVICES </h2>
							<div class="image wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
								<img src="/images/services/6.jpg" alt="" />
							</div>
							<p>We offer servers, computers, computer accessories and services by sourcing from local market and from international market as well. Our team of experts is ready to serve you when you are worried due to lack of confidence in “commitment of service”.</p>
							<p>BASALEH GLOBAL SERVICES LIMITED's also offer & Supply, Delivery & Installation </p>
		
							<div class="image-two wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
								<img src="/images/services/Hardware Services_PG.png" alt="" />
								<div class="play-box">
									<a href="https://www.youtube.com/watch?v=kxPCFljwJws" class="lightbox-image video-box"><span class="fa fa-play"><i class="ripple"></i></span></a>
								</div>
							</div>
							<h3>Analyzing Managed Services</h3>
							<p><i>BASALEH GLOBAL SERVICES LIMITED</i> has the expertise and experience to manage an enabling infrastructure and applications and run outsourced operations for large telecom operators smoothly. <p><i>BASALEH GLOBAL SERVICES LIMITED's</i> Managed Services offerings cover the entire array of IT outsourcing services including networks, IT infrastructure, applications and business processes. This provides our customers the best of both worlds - control and flexibility over their information systems without either the pain or cost of running them.</p>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	
	<!-- Info Section -->
	<section class="info-section" style="background-image: url(/images/background/6.jpg)">
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- Logo Column -->
				<div class="logo-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="logo">
							<a href=https://basalehglobal.com"><img src="/images/logo-2.png" alt="" /></a>
						</div>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-pin"></span></div>
						<ul>
							<li><strong>Address</strong></li>
							<li>G6, Barumak Estate, Wuye Abuja.</li>
						</ul>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-phone-call"></span></div>
						<ul>
							<li><strong>Phone</strong></li>
							<li>(+234) 08038012451, 08174212145</li>
						</ul>
					</div>
				</div>
				
				<!-- Info Column -->
				<div class="info-column col-lg-3 col-md-6 col-sm-12">
					<div class="inner-column">
						<div class="icon-box"><span class="flaticon-email-1"></span></div>
						<ul>
							<li><strong>E-Mail</strong></li>
							<li>info@basalehglobal.ng</li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- End Info Section -->
	
	<!-- Main Footer -->
    <footer class="main-footer style-three">
		<div class="pattern-layer-three" style="background-image: url(/images/background/pattern-14.png)"></div>
		<div class="pattern-layer-four" style="background-image: url(/images/background/pattern-15.png)"></div>
		<!--Waves end-->
    	<div class="auto-container">
        	<!--Widgets Section-->
            <div class="widgets-section">
            	<div class="row clearfix">
                	
					<!-- Footer Column -->
					<div class="footer-column col-lg-4 col-md-6 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
						<div class="footer-widget logo-widget">
							<h5>About Company</h5>
							<div class="text">BASALEH GLOBAL SERVICES LIMITED provides one stop solution ICT indigenous Company Incorporate with Corporate Affairs Commission (CAC), to provide ICT solution to International and National Organization, Government and Private, States and Local Government, NGOs in the field of ICT.</div>
						</div>
					</div>
					
					<!-- Footer Column -->
					<div class="footer-column col-lg-3 col-md-6 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
						<div class="footer-widget links-widget">
							<h5>Quick Links</h5>
							<ul class="list-link">
								<li><a href="#">Managed IT services</a></li>
								<li><a href="#">Cloud Services</a></li>
								<li><a href="#">IT support & helpdesk</a></li>
								<li><a href="#">Cyber security</a></li>
								<li><a href="#">Custom Software</a></li>
								<li><a href="#">Free Consultation</a></li>
								<li><a href="#">Our Business Growth</a></li>
							</ul>
						</div>
					</div>
					
                    <!-- Footer Column -->
					<div class="footer-column col-lg-5 col-md-6 col-sm-12 wow zoomIn" data-wow-delay="0ms" data-wow-duration="800ms">
						<div class="footer-widget subscribe-widget">
							<h5>Subscribe Newsletter</h5>
							<div class="text">Sign up today for hints, tips and <br> the latest product news</div>
							<!--Emailed Form-->
							<div class="emailed-form">
								<form method="post" action="#">
									<div class="form-group">
										<input type="email" name="email" value="" placeholder="Enter Your Email" required>
										<button type="submit" class="theme-btn">Subscribe Now</button>
									</div>
								</form>
							</div>
						</div>
					</div>
					
				</div>
			</div>
			
		</div>
		
		<!-- Footer Bottom -->
		<div class="footer-bottom">
			<div class="auto-container">
				<div class="row clearfix">
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<div class="copyright">Copyright &copy; <?php echo date("Y"); ?> by <a href="https://itechwebnig.com.ng/" style="color: #fff;">Itechnology Group</a> . All Rights Reserved.</div>
					</div>
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<ul class="footer-nav">
								<li><a href="about.PHP">About Us</a></li>
								<li><a href="services.PHP">Services</a></li>
								<li><a href="mission.PHP">Mission</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		
	</footer>
	
	
</div>
<!--End pagewrapper-->
<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-arrow-up"></span></div>

<script src="/js/jquery.js"></script>
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="/js/jquery.fancybox.js"></script>
<script src="/js/appear.js"></script>
<script src="/js/parallax.min.js"></script>
<script src="/js/tilt.jquery.min.js"></script>
<script src="/js/jquery.paroller.min.js"></script>
<script src="/js/owl.js"></script>
<script src="/js/wow.js"></script>
<script src="/js/nav-tool.js"></script>
<script src="/js/jquery-ui.js"></script>
<script src="/js/script.js"></script>
<script src="/js/color-settings.js"></script>

</body>
</html>